@host=http://127.0.0.1:3001
@host_vercel=https://music-app-jade-tau.vercel.app/
@jwt_accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiQURNSU4iLCJpYXQiOjE3NjY5ODk4NzEsImV4cCI6MTc2Njk5MDc3MSwic3ViIjoiOWQ0Y2U1Y2QtNjBiZi00M2NlLTk0NTAtYzQyZWY3N2RlMjUwIn0.gIjsUZgxn_Q9KmJMANEf9xF4Hf1iZBAekAnNMLNm2VE

### LOGIN ADMIN ----------------------------------
### 
POST {{host}}/api/auth/login
Content-Type: application/json

{
  "email": "lujan9814@gmail.com",
  "password": "matiaslujan"
}

### LOGIN USER ----------------------------------
### 
POST {{host}}/api/auth/login
Content-Type: application/json

{
  "email": "usertest@gmail.com",
  "password": "Usertest"
}

### CASO NEGATIVO ----------------------------------
### Password incorrecta
POST {{host}}/api/auth/login
Content-Type: application/json

{
  "email": "usertest@gmail.com",
  "password": "incorrecto"
}