@host=http://127.0.0.1:3001
@jwt_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWJqZWN0IjoiNWRmOTdiZDEtOGRiOS00YmYzLWIzZWQtOTc4YjI2OTQzMGM4IiwiZW1haWwiOiJ1c2VydGVzdEBnbWFpbC5jb20iLCJub21icmUiOiJVc2VydGVzdCIsImFwZWxsaWRvIjoiVXNlcnRlc3QiLCJyb2xlIjoiVVNFUiIsImlhdCI6MTc2Mzk2MjA2MywiZXhwIjoxNzY0MDQ4NDYzfQ.InPVTDwqSmV7UODM8XXNB6hDkI8_4D83YF7OnxKtIUE

###
POST {{host}}/api/song/play/5374f0dd-51cf-4c47-9621-796a390bb9f7
Authorization: Bearer {{jwt_token}}