@host=http://127.0.0.1:3001

GET {{host}}/api/songs

###
GET {{host}}/api/song/f48689e6-1885-4559-81d6-5fe04e33d6ea

###
DELETE {{host}}/api/song/21e9de2e-de84-40e2-8a70-81dadb42c32a

###
POST {{host}}/api/song
Content-Type: application/json

{
    "titulo":"Como te voy a olvidar",
    "artista": "Los angeles azules"
}

###
PATCH {{host}}/api/song/21e9de2e-de84-40e2-8a70-81dadb42c32a
Content-Type: application/json

{
  "titulo": "Sabado a la noche",
  "artista": "Juana la loca",
  "album": "Ni idea pa",
  "genero": ["Rock Argentino"],
  "duracion": 200,
  "portada": "https://i.scdn.co/image/juana-la-loca",
  "fecha_lanzamiento": "2006-03-25"
}

###
PATCH {{host}}/api/song/21e9de2e-de84-40e2-8a70-81dadb42c32a
Content-Type: application/json

{
  "album": "Meteora (Deluxe Edition)",
  "portada": "https://i.scdn.co/image/AAAAAAAAAAAAAAAAAA"
}