@host=http://127.0.0.1:3001
@jwt_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWJqZWN0IjoiYzUyY2IzZTktODljNC00YWVlLWJmM2QtZjMxM2QwMjMzN2E1IiwiZW1haWwiOiJ1c2VyQGdtYWlsLmNvbSIsIm5vbWJyZSI6Ik1hdGlhcyIsImFwZWxsaWRvIjoiTHVqYW4iLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE3NjM5MzI3NTksImV4cCI6MTc2NDAxOTE1OX0.3sbSYY1DPx1yyk7IKzIZnCQFArVWRsFhZfI6PKzMBQg


###
GET {{host}}/api/song/songs
Authorization: Bearer {{jwt_token}}
Content-Type: application/json

###
GET {{host}}/api/song/b92e15ee-1b98-415a-9ba1-af16ec98a380
Authorization: Bearer {{jwt_token}}
Content-Type: application/json


###
POST {{host}}/api/song/create
Authorization: Bearer {{jwt_token}}
Content-Type: application/json

{
    "titulo":"shape of you",
    "artista": "ed sheeran"
}

###
PATCH {{host}}/api/song/b92e15ee-1b98-415a-9ba1-af16ec98a380
Authorization: Bearer {{jwt_token}}
Content-Type: application/json

{
  "album": "TEST",
  "portada": "TEST"
}

###
DELETE {{host}}/api/song/b92e15ee-1b98-415a-9ba1-af16ec98a380
Authorization: Bearer {{jwt_token}}
Content-Type: application/json
