@host=http://127.0.0.1:3001
@jwt_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWJqZWN0IjoiNWRmOTdiZDEtOGRiOS00YmYzLWIzZWQtOTc4YjI2OTQzMGM4IiwiZW1haWwiOiJ1c2VydGVzdEBnbWFpbC5jb20iLCJub21icmUiOiJVc2VydGVzdCIsImFwZWxsaWRvIjoiVXNlcnRlc3QiLCJyb2xlIjoiVVNFUiIsImlhdCI6MTc2Mzk2NDQ0MiwiZXhwIjoxNzY0MDUwODQyfQ.S8YKM1ny9UAjbGzQSQdALc0Bxg43vWmtHKUt513LZE8

###
GET {{host}}/api/stats/top-songs?limit=3
Authorization: Bearer {{jwt_token}}

###
GET {{host}}/api/stats/me/top-songs?limit=3
Authorization: Bearer {{jwt_token}}

###
GET {{host}}/api/stats/me/top-artists?limit=3
Authorization: Bearer {{jwt_token}}

###
GET {{host}}/api/stats/me/top-albums?limit=3
Authorization: Bearer {{jwt_token}}

###
GET {{host}}/api/stats/me/top-genres?limit=3
Authorization: Bearer {{jwt_token}}

###
GET {{host}}/api/stats/export?limit=3
Authorization: Bearer {{jwt_token}}

> ../exports/musicapp_stats.xlsx