@host=http://127.0.0.1:3001

GET {{host}}/api/users

###
GET {{host}}/api/user/4960a99a-fe12-4fb2-8008-8aab56dc161c

###
DELETE {{host}}/api/user/a3700d25-300f-498d-b558-e4f89bb3f038

###
POST {{host}}/api/user/create
Content-Type: application/json

{
    "nombre":"Matias",
    "apellido":"Lujan",
    "fecha_nacimiento":"1998-07-14", //año-mes-dia
    "password":"matiaslujan",
    "email": "lujan9814@gmail.com"
}

###
PATCH {{host}}/api/user/7d51476a-6f13-4ba8-80d7-9334dfcf9e64
Content-Type: application/json

{
  "nombre": "Juan P. Updated",
  "email": "updated@example.com"
}
